# Generated by Django 4.2.6 on 2023-10-28 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.TextField()),
                ('diagnostico', models.TextField()),
                ('receta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12, verbose_name='RUT')),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, verbose_name='RUT')),
                ('fecha_nacimiento', models.DateField()),
                ('sistema_salud', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('medicacion', models.CharField(max_length=100)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes_asignados', to='galenos_app.medico')),
            ],
        ),
        migrations.AddField(
            model_name='medico',
            name='pacientes',
            field=models.ManyToManyField(related_name='citas_medico', through='galenos_app.Cita', to='galenos_app.paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galenos_app.medico'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galenos_app.paciente'),
        ),
    ]
