# Generated by Django 4.2.6 on 2023-12-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galenos_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='receta',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='medicacion',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sistema_salud',
            field=models.CharField(choices=[('Fonasa', 'Fonasa'), ('Isapre', 'Isapre')], max_length=100),
        ),
    ]
