# Generated by Django 4.2.6 on 2023-11-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galenos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='edad',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='genero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.BooleanField(default=False),
        ),
    ]
