# Generated by Django 4.2.6 on 2023-11-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galenos_app', '0002_medico_edad_medico_genero_paciente_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='medicacion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
