# Generated by Django 4.2.6 on 2023-11-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galenos_app', '0003_alter_paciente_medicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10),
        ),
    ]
